[tool.poetry]
name = "full-stack-fastapi-template"
version = "0.1.0"
description = ""
authors = ["bohdants96 <bohdantsisinskyi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
