"""кÑremake transaction

Revision ID: 116e875b0c1e
Revises: f0c8bd2ac442
Create Date: 2024-07-03 17:07:11.542781

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "116e875b0c1e"
down_revision: Union[str, None] = "f0c8bd2ac442"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("credits_purchased", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "credits_purchased")
    # ### end Alembic commands ###
