"""street_people

Revision ID: 19404f740ec8
Revises: 37fa7433d358
Create Date: 2024-09-04 15:31:01.521011

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19404f740ec8"
down_revision: Union[str, None] = "37fa7433d358"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "peoplelead",
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("peoplelead", "street")
    # ### end Alembic commands ###
