"""empty message

Revision ID: 1ad84ab6b7ed
Revises: 637217d3d77b
Create Date: 2024-05-25 16:22:09.342415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1ad84ab6b7ed'
down_revision: Union[str, None] = '637217d3d77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapeddata', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrapeddata', 'website')
    # ### end Alembic commands ###
