"""status_search_history

Revision ID: 36f18e394393
Revises: 12b98738c09e
Create Date: 2024-07-08 13:50:20.430268

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36f18e394393"
down_revision: Union[str, None] = "12b98738c09e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "searchhistory",
        sa.Column(
            "task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "searchhistory",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "searchhistory", "source", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "searchhistory", "source", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("searchhistory", "status")
    op.drop_column("searchhistory", "task_id")
    # ### end Alembic commands ###
