"""people-lead, work, house

Revision ID: 37fa7433d358
Revises: 690311c1c05d
Create Date: 2024-08-30 11:49:36.078632

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37fa7433d358"
down_revision: Union[str, None] = "690311c1c05d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "peoplelead",
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "peoplelead",
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("peoplelead", "state")
    op.drop_column("peoplelead", "city")
    # ### end Alembic commands ###
