"""add avatar

Revision ID: 458ea5c4d23c
Revises: 8e015e72ed7e
Create Date: 2024-06-28 15:43:00.389941

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "458ea5c4d23c"
down_revision: Union[str, None] = "8e015e72ed7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###
