"""bussiness_owner

Revision ID: 5907b6bdd7b8
Revises: c68a14f7b773
Create Date: 2024-08-12 17:32:24.344790

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5907b6bdd7b8"
down_revision: Union[str, None] = "c68a14f7b773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businessownerinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_socials", sa.JSON(), nullable=True),
        sa.Column(
            "person_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "person_position",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("person_socials", sa.JSON(), nullable=True),
        sa.Column(
            "person_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("business_management", sa.JSON(), nullable=True),
        sa.Column(
            "person_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "person_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("business_lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_lead_id"],
            ["businesslead.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("businessownerinfo")
    # ### end Alembic commands ###
