"""Ðadd owner and conpany email

Revision ID: 5c226d765cae
Revises: 116e875b0c1e
Create Date: 2024-07-04 16:58:42.103603

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c226d765cae"
down_revision: Union[str, None] = "116e875b0c1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesslead",
        sa.Column(
            "company_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "businesslead",
        sa.Column(
            "owner_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesslead", "owner_email")
    op.drop_column("businesslead", "company_email")
    # ### end Alembic commands ###
