"""empty message

Revision ID: 636fc5d3fa36
Revises: cd3ae619b6d5
Create Date: 2024-06-05 20:20:19.302390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636fc5d3fa36'
down_revision: Union[str, None] = 'cd3ae619b6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessleadaccesslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('business_leads_ids', sa.JSON(), nullable=True),
    sa.Column('free_access', sa.Boolean(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessleadaccesslog')
    # ### end Alembic commands ###
