"""empty message

Revision ID: 63d6808554ee
Revises: 1ad84ab6b7ed
Create Date: 2024-05-26 17:07:58.280252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d6808554ee'
down_revision: Union[str, None] = '1ad84ab6b7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapeddata', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scrapeddata', 'business_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scrapeddata', 'company_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scrapeddata', 'company_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scrapeddata', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scrapeddata', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapeddata', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scrapeddata', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scrapeddata', 'company_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scrapeddata', 'company_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scrapeddata', 'business_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scrapeddata', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
