"""add credits purch to transaction

Revision ID: 66d8474ef5a9
Revises: 5ae7a44ff982
Create Date: 2024-07-03 16:50:09.207561

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66d8474ef5a9"
down_revision: Union[str, None] = "5ae7a44ff982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
