"""add_ticket

Revision ID: 78d5919d4488
Revises: 8d5763b0f13f
Create Date: 2024-06-20 00:55:06.979696

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78d5919d4488"
down_revision: Union[str, None] = "8d5763b0f13f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "mobile_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "message", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_email"), "ticket", ["email"], unique=False)
    op.alter_column(
        "businesslead",
        "received_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "businesslead",
        "received_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_index(op.f("ix_ticket_email"), table_name="ticket")
    op.drop_table("ticket")
    # ### end Alembic commands ###
