"""user none in search history

Revision ID: 80c7c767b1a7
Revises: 36f18e394393
Create Date: 2024-07-10 21:08:04.809054

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80c7c767b1a7"
down_revision: Union[str, None] = "36f18e394393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "searchhistory", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "searchhistory", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
