"""add time update

Revision ID: 8e015e72ed7e
Revises: e1505ad33dd7
Create Date: 2024-06-28 15:23:15.231507

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e015e72ed7e"
down_revision: Union[str, None] = "e1505ad33dd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("last_password_reset_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_password_reset_time")
    # ### end Alembic commands ###
