"""looked_owner

Revision ID: 9a3dea6af407
Revises: 5907b6bdd7b8
Create Date: 2024-08-18 18:37:38.127508

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3dea6af407"
down_revision: Union[str, None] = "5907b6bdd7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrapereventdata",
        sa.Column("looked_owner", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrapereventdata", "looked_owner")
    # ### end Alembic commands ###
