"""remake received_date

Revision ID: be0971ab9fe0
Revises: 9a11e6da3e1e
Create Date: 2024-06-12 20:09:42.191692

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0971ab9fe0"
down_revision: Union[str, None] = "9a11e6da3e1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
