"""add other info business

Revision ID: c68a14f7b773
Revises: 80c7c767b1a7
Create Date: 2024-07-24 12:12:04.261387

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c68a14f7b773"
down_revision: Union[str, None] = "80c7c767b1a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesslead",
        sa.Column(
            "primary_category",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "businesslead",
        sa.Column("rating", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "businesslead",
        sa.Column(
            "count_reviews", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "businesslead",
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "businesslead", sa.Column("schedule_dict", sa.JSON(), nullable=True)
    )
    op.add_column("businesslead", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column(
        "businesslead", sa.Column("services", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesslead", "services")
    op.drop_column("businesslead", "tags")
    op.drop_column("businesslead", "schedule_dict")
    op.drop_column("businesslead", "description")
    op.drop_column("businesslead", "count_reviews")
    op.drop_column("businesslead", "rating")
    op.drop_column("businesslead", "primary_category")
    # ### end Alembic commands ###
