"""add other info business

Revision ID: d902d8359074
Revises: 094b2b12d289
Create Date: 2024-07-24 10:38:42.820753

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d902d8359074"
down_revision: Union[str, None] = "094b2b12d289"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesslead", sa.Column("schedule_dict", sa.JSON(), nullable=True)
    )
    op.add_column("businesslead", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column(
        "businesslead", sa.Column("services", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesslead", "services")
    op.drop_column("businesslead", "tags")
    op.drop_column("businesslead", "schedule_dict")
    # ### end Alembic commands ###
