"""free

Revision ID: defa3d56e95d
Revises: 2d8d5e4d01d7
Create Date: 2024-06-10 17:37:50.008308

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "defa3d56e95d"
down_revision: Union[str, None] = "2d8d5e4d01d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("free_credit", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "free_credit")
    # ### end Alembic commands ###
