"""empty message

Revision ID: f63713aad844
Revises: c7667b292b4b
Create Date: 2024-06-08 13:56:54.147052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f63713aad844'
down_revision: Union[str, None] = 'c7667b292b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapereventdata', 'task_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('scrapereventdata', 'scraped_results',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scrapereventdata', 'total_results',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapereventdata', 'total_results',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scrapereventdata', 'scraped_results',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scrapereventdata', 'task_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
