"""business_log_add

Revision ID: f79929f5f2c9
Revises: 78d5919d4488
Create Date: 2024-06-24 15:39:34.527611

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f79929f5f2c9"
down_revision: Union[str, None] = "78d5919d4488"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businessleadaccesslog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_time", sa.DateTime(), nullable=False),
        sa.Column("business_leads_ids", sa.JSON(), nullable=True),
        sa.Column("free_access", sa.Boolean(), nullable=False),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("businessleadaccesslog")
    # ### end Alembic commands ###
